### ISSUE TITLE
Usage with electronjs

### ISSUE THREAD

**Issue by mnesarco** [puxiao/using-orbitcontrols-in-worker#1]
Hi, Thank you for this excelent resource. It works perfectly in browser using worker and direct mode, but in electron only works in direct mode. When used in worker mode the screen is just black.

Do you have any clue of what could be the problem?

**Comment by mnesarco** [comment]
For some reason the typescript worker doesn't work, but i changed it to plain javascript and everything works now. The rest of the code is in typescript.

**Comment by puxiao** [comment]
Sorry, I've never used electronjs.

I found a difference: 

https://github.com/puxiao/using-orbitcontrols-in-worker/blob/main/package.json
"typescript": "^4.1.2"

https://github.com/electron/electron-quick-start-typescript/blob/master/package.json
"typescript": "^3.9.5"

Is that the reason?

**Comment by mnesarco** [comment]
Hi @puxiao , no the problem is not TypeScript per se, it is something related to webpack + worker-loader + typescript chain. But removing TypeScript from the recipe makes webpack happy. Anyway the only file with this problem is the worker and it is a very small file, so  converting it to plain javascript was not a big deal and everything works.

Thank you again for this resource.

**Comment by puxiao** [comment]
you are welcome.
